name: Build wheels

on:
  push:
    tags:
      - '*.*.*'   # Para tags como '1.2.3'
      - '*.*'     # Para tags como '1.2'
  workflow_dispatch:

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist

  release:
    name: Create GitHub Release
    needs: build  # espera a que termine el job de build en todas las plataformas
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: dist/linux
      - uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: dist/windows
      - uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: dist/macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            dist/**/*  # Esto sube todos los .whl generados
